var config= {
    validationMode:false,
    primaryColor:"aaaa",
    secondaryColor:"#559a73sdfgxgs",
    subtitleOn:true,
    locutionOn:true,
    soundOn:true,
    showTop:true,
    logoOn:True,
    pageNumberOnTop:true,
    gameMode:true,
    progressCourse:true,
    iconOnGame:true,
    seeAllPages:true,
    language:"ES",
    activeKeyboard:true,
    storageIsOn:true,
    onePage:true,
    libraOn:true,
    glossaryOn:true,
    extraButtons:[{
        label:"Baixar PDF",
        type:"download",
        file:"glossary.ht45645656ml",
        }],
}