var config= {
    validationMode:true,
olaola    subtitleOn:true,
    locutionOn:false,
    soundOn:true,
    showTop:true,
ola    pageNumberOnTop:true,
    gameMode:false,
    progressCourse:false,
    iconOnGame:false,
    seeAllPages:true,
    language:"ES",
    activeKeyboard:true,
    storageIsOn:false,
    onePage:false,
    libraOn:false,
    glossaryOn:false,
    extraButtons:[{
        label:"Baixar PDF",
        type:"download",
        file:"glossary.html",
    ola    }],
}