var config= {
    validationMode:true,
    primaryColor:"#3862a6",
    secondaryColor:"#559a73",
    subtitleOn:true,
    soundOn:true,
    showTop:true,
    pageNumberOnTop:true,
    logoOn:true,
    progressCourse:false,
    gameMode:false,
    language:"pt",
    onePage:false,
    libraOn:false,
    glossaryOn:false,
    extraButtons:[
        {label:"Baixar PDF 1",
        file:"glossary.html"},
        {label:"Baixar PDF 2",
        file:"glossary.html"},
        {label:"Baixar PDF 3",
        file:"glossary.html"},
        {label:"Baixar PDF 4",
        file:"glossary.html"},
        ],
}